mini_project_max/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web_app.urls")),
    # ------ 1 register veikia ------
    path("register/", user_views.register, name="register"),
    # ----- 1 login veikia -----
    # path("login/", user_views.CustomLogin, name="login"),
    # ----- 2 login veikia -----
    path(
        "login/",
        user_views.CustomLogin.as_view(template_name="users/login.html"),
        name="login",
    ),
    # ----- 3 login veikia -----
    # path("login/", user_views.login_page, name="login"),
    path("logout/", user_views.SignOutView.as_view(), name="logout"),
    # path("profile/<str:username>", user_views.profile, name="profile"),  # function-based view
    path(
        "profile/<str:username>",
        user_views.ProfilePostListView.as_view(),
        name="profile",
    ),  # class-based view
    path(
        "profile/<str:username>/update", user_views.ProfileUpdate, name="profile-update"
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_app/urls.py
from django.urls import path
from web_app import views as web_app_views

# from .views import PostListView

urlpatterns = [
    path("", web_app_views.PostListView.as_view(), name="home"),
    path("post/<int:pk>", web_app_views.PostDetailView.as_view(), name="post-detail"),
    path("post/<int:pk>/like", web_app_views.PostLike, name="post-like"),
    path(
        "post/<int:pk>/delete",
        web_app_views.PostDeleteView.as_view(),
        name="post-delete",
    ),
    path(
        "post/<int:pk>/update",
        web_app_views.PostUpdateView.as_view(),
        name="post-update",
    ),
    path("upload/", web_app_views.post_upload, name="post-upload"),
]

users/models.py
from django.db import models
from web_app.models import Post
from django.utils import timezone
from PIL import Image

# ------ 1 login veikia -------
# from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# from django.contrib.auth import get_user_model

# ------ 2 ir 3 login veikia (užkomentuoti naudojant 1 login variantą) -------
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend
from django.core.exceptions import ValidationError


# Create your models here.
# ------ 2 ir 3 login variantams ------
class EmailBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        User = get_user_model()
        # model = User.objects.get()
        try:
            # this allows the username value provided by a user to be treated
            # as an email field for authentication purposes. If a user matches
            # the email provided as the username value, then the
            # try-except-else block# performs a call to check_password()
            # to validate the password against the matching user. If the
            # password matches, authenticate() returns the authenticated user,
            # if the password doesn't match authententicate() returns None.
            user = User.objects.get(email=username)
        except User.DoesNotExist:
            raise ValidationError("Įvesti neteisingi duomenys.")
            # return None
            # ------- 3 --------
            # error_message = "Įvesti neteisingi duomenys."
        else:
            if user.check_password(password) and self.user_can_authenticate(user):
                return user
        return None


# ---------- 1 login veikia (šitam nereikia EmailBackend) ------------
# ----------- reikia keist pati User modeli ir UserManager ------------
# class UserManager(BaseUserManager):
#     def create_user(
#         self,
#         email,
#         username,
#         password=None,
#         is_active=True,
#         is_staff=False,
#         is_admin=False,
#     ):  # put here all REQUIRED FIELDS
#         if not email:
#             raise ValueError("Users must have an email address")
#         if not password:
#             raise ValueError("Users must have a password")

#         user_obj = self.model(
#             email=self.normalize_email(email)
#         )  # Normalizes email addresses by lowercasing the domain portion of the email address.
#         user_obj.set_password(password)  # set password or change user password
#         user_obj.username = username
#         user_obj.staff = is_staff
#         user_obj.admin = is_admin
#         user_obj.active = is_active
#         user_obj.save(using=self._db)
#         return user_obj

#     def create_staffuser(self, email, password=None):
#         user = self.create_user(email, username, password=password, is_staff=True)
#         return user

#     def create_superuser(self, email, username=None, password=None):
#         user = self.create_user(
#             email, username, password=password, is_staff=True, is_admin=True
#         )
#         return user


# class User(AbstractBaseUser):
#     email = models.EmailField(verbose_name="El. paštas", max_length=255, unique=True)
#     username = models.CharField(max_length=100, unique=True, null=True)
#     # fullname = models.CharField(max_length=255, blank=True, null=True)
#     active = models.BooleanField(default=True)  # can login
#     staff = models.BooleanField(default=False)  # staff user non superuser
#     admin = models.BooleanField(default=False)  # superuser
#     timestamp = models.DateTimeField(default=timezone.now)
#     # confirm     = models.BooleanField(default=False)
#     # confirmed_date     = models.DateTimeField(default=False)

#     objects = UserManager()

#     USERNAME_FIELD = "email"
#     REQUIRED_FIELDS = [
#         "username"
#     ]  # Email & Password are required by default, we add username.

#     def __str__(self):
#         return self.email

#     def get_full_name(self):
#         return self.email

#     def get_short_name(self):
#         return self.email

#     def has_perm(self, perm, obj=None):
#         return True

#     @property
#     def is_staff(self):
#         return self.staff

#     @property
#     def is_admin(self):
#         return self.admin

#     @property
#     def is_active(self):
#         return self.active


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField(blank=True, verbose_name="About Me")
    image = models.ImageField(default="default_pic.jpg", upload_to="profile_pics/")
    # video = models.ForeignKey(
    #    Post, on_delete=models.CASCADE, null=True, blank=True
    # )

    def __str__(self):
        return f"{self.user.username} Profile"

    # automatically resize the image file that user uploads:
    # save() is a method that gets run after our model is saved
    # (it already exists in our parent class, so we're gonna override it):
    def save(self, *args, **kwargs):
        # run save method of our parent class using super() before resizing, otherwise we'll have an error:
        # no such file or directory.
        # when overriding model's save method in Django, we should also pass
        # *args and **kwargs to overridden method!!!
        # Otherwise, we get 'TypeError - save() got an unexpected keyword argument 'force_insert' error'
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        # if we get "cannot write mode P as JPEG" error, convert to RGB:
        if img.mode != "RGB":
            img = img.convert("RGB")
        if img.height > 96 and img.width > 96:
            output_size = (96, 96)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Comment(models.Model):
    posted_by = models.ForeignKey(User, on_delete=models.PROTECT)
    comment = models.TextField(max_length=400, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_on = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f'Comment: "{self.comment}" by {self.posted_by}'


class Like(models.Model):

    LIKE = "Patinka"
    UNLIKE = "Daugiau nepatinka"

    LIKE_CHOICES = [
        (LIKE, "Patinka"),
        (UNLIKE, "Daugiau nepatinka"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default="Patinka", max_length=25)

    def __str__(self):
        return str(self.post)

web_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    title = models.CharField(max_length=150, blank=False)
    likes = models.PositiveIntegerField(default=0)
    video = models.FileField(upload_to="videos/", null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    liked = models.ManyToManyField(User, default=None, blank=True, related_name="liked")

    def __str__(self):
        return f"{self.title} (uploaded by {self.user.username})"

    @property
    def num_of_likes(self):
        return self.liked.all().count()

web_app/views.py
from .models import Post
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from .forms import (
    PostUploadForm,
    CommentForm,
    ChangeTitleForm,
)
from users.models import Profile, Comment, Like
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
)
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
import os
from django.conf import settings

# Create your views here.


class PostListView(ListView):
    model = Post
    template_name = "web_app/home.html"
    context_object_name = "posts"
    ordering = ["-date_posted"]  # latest to oldest
    paginate_by = 9


class PostDetailView(DetailView):
    model = Post
    template_name = "web_app/post_detail.html"
    form_class = CommentForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        post = Post.objects.get(pk=self.kwargs["pk"])
        comments = Comment.objects.filter(post__pk=self.kwargs["pk"])
        context = {"comment_form": form, "comments": comments, "post": post}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        post = Post.objects.get(pk=self.kwargs["pk"])
        comments = Comment.objects.filter(post__pk=self.kwargs["pk"])
        form = self.form_class(request.POST)
        context = {"comment_form": form, "comments": comments, "post": post}
        if form.is_valid():
            user = request.user
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.posted_by = user
            new_comment.save()
            return redirect("post-detail", self.kwargs["pk"])
        else:
            # perkrauti puslapį, bet gražinti POST formą su klaidą:
            return render(request, self.template_name, context)


@login_required
def PostLike(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.user not in post.liked.all():
        post.liked.add(request.user)
    else:
        post.liked.remove(request.user)

    # čia duomenų bazei, sukurti like objektą arba atnaujinti egzistuojantį:
    like, created = Like.objects.get_or_create(user=request.user, post=post)

    # kai vartotojas paspaudzia mygtuka:
    if not created:  # jeigu objektas egzistuoja (update'inti ji)
        if like.value == "Patinka":  # jeigu jo value DB lygus Patinka
            like.value = "Daugiau nepatinka"  # pakeisti i Daugiau nepatinka
        else:
            like.value = "Patinka"

    # tas pats:
    # try:
    #     like = Like.objects.get(user=request.user, post=post)
    #     if like.value == "Patinka":
    #         like.value = "Daugiau nepatinka"
    #     else:
    #         like.value = "Patinka"
    # except Like.DoesNotExit:
    #     like = Like(user=request.user, post=post)

    like.save()
    post.likes = post.liked.all().count()
    post.save()

    return redirect("post-detail", post.id)


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = "web_app/post_detail.html"

    # pk_url_kwarg = "pk"
    # model = Post

    # def get_success_url(self, **kwargs):
    #     user = self.object.user
    #     return reverse("profile", kwargs={"username": user.username})

    # def test_func(self):
    #     post = self.get_object()
    #     # check if the logged in user is the post creator:
    #     if request.user == post.user:
    #         return True
    #     return False

    # tas pats kas viršuje:
    def get_object(self, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs.get("pk"))
        return post

    def test_func(self):
        post = get_object_or_404(Post, pk=self.kwargs.get("pk"))
        # check if the logged in user is the post creator:
        if (self.request.user == post.user) or (self.request.user.is_superuser):
            return True
        return False  # 403 Forbidden

    def get_success_url(self, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs.get("pk"))
        user = post.user
        os.remove(os.path.join(settings.MEDIA_ROOT, f"{post.video}".replace('/', '\\')))
        # lazy version of the reverse URL resolver. Unlike the traditional reverse function,
        # reverse_lazy won't execute until the value is needed.
        # It is useful because it prevent 'Reverse Not Found' exceptions when working with
        # URLs that may not be immediately known.It’s prevent to occur error when URLConf is not loaded:
        return reverse_lazy("profile", kwargs={"username": user.username})


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = "web_app/post_detail.html"
    form_class = ChangeTitleForm

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        title_form = self.form_class
        comments = Comment.objects.filter(post__pk=self.kwargs["pk"])
        context = {"title_form": title_form, "comments": comments, "post": post}
        return render(request, self.template_name, context)

    def get_success_url(self, **kwargs):
        post = self.get_object()
        return reverse("post-detail", kwargs={"pk": post.id})

    def test_func(self):
        post = self.get_object()
        if (self.request.user == post.user) or (self.request.user.is_superuser):
            return True
        return False  # 403 Forbidden

    def post(self, request, *args, **kwargs):
        post = self.get_object()
        form = self.form_class(request.POST)
        comments = Comment.objects.filter(post__pk=self.kwargs["pk"])
        context = {"title_form": form, "post": post, "comments": comments}
        if form.is_valid():
            new_title = form.cleaned_data.get("title")
            post.title = new_title
            post.save()
            return redirect("post-detail", self.kwargs["pk"])
        # errors:
        else:
            # perkrauti puslapį, bet gražinti POST formą su klaidą:
            return render(request, self.template_name, context)


@login_required
def post_upload(request):
    if request.method == "POST":
        form = PostUploadForm(request.POST, request.FILES)
        if form.is_valid():
            # title = form.cleaned_data.get("title")
            # video = form.cleaned_data.get("video")
            # without user error: NOT NULL constraint failed: users_post.user_id:
            # You need to add the value of the user field in Post object.
            # For that, before saving the post, you can attach the user from request.user.
            # Using form.save(commit=False) will create a Post instance 'in memory', but not yet saved
            # in the Database, then add the user to that Post instance (add some changes before saving it)
            post = form.save(commit=False)
            post.user = request.user
            # post.title = title
            # post.video = video
            post.save()
            return redirect("profile", request.user.username)
    else:
        form = PostUploadForm()

    context = {"form": form, "title": "Įkelti video"}
    return render(request, "web_app/post_upload.html", context)

web_app/templates/web_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'web_app/main.css' %}">

    {% if title %}
    <title>Web App - {{ title }}</title>
    {% else %}
    <title>Web App</title>
    {% endif %}
</head>

{% block css %}
{% endblock css %}

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="navbar-popup">
            <div class="container-fluid">
                <a class="navbar-brand mr-4" href="{% url 'home' %}">Logo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if request.user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'post-upload' %}">Įkelti video</a>
                        <a class="nav-item nav-link" href="{% url 'profile' user.username %}">Profilis</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Atsijungti</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{% url 'register' %}">Registruotis</a>
                        <a class="nav-item nav-link" href="{% url 'login' %}">Prisijungti</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" style="margin-top: 56px;">
        {{ message }}
    </div>
    <section class="main" style="margin-top: 0;">
        {% block content-with-message %}
        {% endblock content-with-message %}
    </section>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script>

        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

        function IkeltiVideoValidatorius() {
            var title_input = document.getElementById("id_title");
            var video_input = document.getElementById("id_video");
            if (title_input.value == '' && video_input.value == '') {
                document.getElementById('id_title').classList.add('is-invalid')
                document.getElementById('id_video').classList.add('is-invalid')
                document.getElementById("error_title_required")
                    .innerHTML = "<strong>Šis laukas yra privalomas.</strong>";
                document.getElementById("error_video_required")
                    .innerHTML = "<strong>Šis laukas yra privalomas.</strong>";
                return false; // stops the submission of form
            }
            if (title_input.value == '' || video_input.value == '') {
                if (title_input.value == '') {
                    document.getElementById('id_title').classList.add('is-invalid')
                    document.getElementById("error_title_required")
                        .innerHTML = "<strong>Šis laukas yra privalomas.</strong>";
                    return false; // stops the submission of form
                }
                if (video_input.value == '') {
                    document.getElementById('id_video').classList.add('is-invalid')
                    document.getElementById("error_video_required")
                        .innerHTML = "<strong>Šis laukas yra privalomas.</strong>";
                    return false; // stops the submission of form
                }

            }
            return true;
        }

        function KeistiAntraste() {
            document.getElementById('popup-background').style.display = 'block';
        }

        function UzdarytiPopup() {
            document.getElementById('popup-background').style.display = 'none';
        }

        function KeistiAntrasteValidatorius() {
            var title_input = document.getElementById("id_title");
            if (title_input.value == '') {
                document.getElementById('id_title').classList.add('custom-invalid')
                document.getElementById("error_title_required")
                    .innerHTML = "<strong>Pakeiskite pavadinimą.</strong>";
                return false; // stops the submission of form
            }
            return true;
        } 
    </script>
</body>

</html>

web_app/templates/web_app/home.html
{% extends 'web_app/base.html' %}

{% block content %}
<section class="main">
    <div class="container container-main">
        <div id='home-profile-videos' class="profile-videos">
            {% for post in posts %}
            <div class="wrapper-main">
                <div class="video-main">
                    <video width='375' height="240" controls>
                        <source src='{{ post.video.url }}' type='video/mp4'>
                        Your browser does not support the video tag.
                    </video>
                </div>
                <div class="text-main">
                    <a href="{% url 'post-detail' post.pk %}">
                        <p>{{ post.title }} (uploaded by {{ post.user }})</p>
                    </a>
                    <p>{{ post.likes }} likes</p>
                </div>
            </div>
            {% endfor %}
        </div>
        {% include 'web_app/pages.html' %}
    </div>
</section>
{% endblock content %}

web_app/templates/web_app/post_detail.html
{% extends 'web_app/base.html' %}

{% block content %}
<section class="main">
    <div class="container container-main" id="container-popup">
        <div id="popup-background">
            <div id="popup-title" class="popupTitle">
                <p>Keisti antraštę</p>
                <form action="{% url 'post-update' post.pk %}" method="POST" novalidate
                    onsubmit='return KeistiAntrasteValidatorius()'>
                    {% csrf_token %}
                    <input id="id_title" type="text" name="title" maxlength="150" autocapitalize="none"
                        class="textinput textInput title-input" required>
                    <p id="error_title_required" class="custom-error-text"></p>
                    <!-- errors: -->
                    {% if title_form.errors %}
                    {% for field in title_form %}
                    {% for error in field.errors %}
                    <p class="invalid-feedback-custom"><strong>{{ error|escape }}</strong></p>
                    {% endfor %}
                    {% endfor %}
                    {% endif %}
                    <div class="title-button-wrapper">
                        <button class="button-popup" id="button-change-title" type="submit">Saugoti</button>
                        <button class="button-popup" id="button-decline" type="button"
                            onclick="UzdarytiPopup()">Atšaukti</button>
                    </div>
                </form>
            </div>
        </div>
        <div id='video-detail' class="profile-videos">
            <div class="" style="width: 963px">
                <div class="text-main">
                    <p>Įkėlė: <a href="{% url 'profile' post.user.username %}">{{ post.user }}</a></p>
                    <p>{{ post.date_posted|date:'Y-m-d' }}</p>
                </div>
                <video width='963' controls>
                    <source src='{{ post.video.url }}' type='video/mp4'>
                    Your browser does not support the video tag.
                </video>
                <div class="text-main">
                    <p>{{ post.title }} (uploaded by {{ post.user }})</p>
                    {% if not request.user.is_authenticated %}
                    <p>{{ post.liked.all.count }} likes</p>
                    {% else %}
                    {% if request.user == post.user or request.user.is_superuser %}
                    <div class="form-wrapper">
                        <form action="{% url 'post-delete' post.id %}" method="POST" class="text-main"
                            id="button-delete">
                            {% csrf_token %}
                            <button class="btn btn-custom btn-outline-info" id="btn-like"
                                type="submit">Ištrinti</button>
                        </form>
                        <button class="btn btn-custom btn-outline-info" id="btn-update2" type="button"
                            onclick="KeistiAntraste()">Keisti antraštę</button>
                    </div>
                    {% endif %}
                    <form action="{% url 'post-like' post.id %}" method="POST" class="text-main">
                        {% csrf_token %}
                        <!-- <input type="hidden" name="post_id" value="{{ post.id }}"> -->
                        <p style="margin-right: 7px">{{ post.liked.all.count }} patiktukai</p>
                        {% if request.user not in post.liked.all %}
                        <button class="btn btn-custom btn-outline-info" id="btn-like" type="submit">Patinka</button>
                        {% else %}
                        <button class="btn btn-custom btn-outline-info" id="btn-like" type="submit">Daugiau
                            nepatinka</button>
                        {% endif %}
                    </form>
                    {% endif %}
                </div>
            </div>
            <div class="comments-wrapper">
                <h5>Komentarai</h5>
                {% for comment in comments %}
                <p>{{ comment.posted_by }}</p>
                <p>{{ comment.comment }}</p>
                <hr>
                {% endfor %}
                {% if user.is_authenticated %}
                <h5>Rašyti komentarą:</h5>
                <form action="" method="POST" novalidate>
                    {% csrf_token %}
                    <label for="id_comment"></label>
                    <textarea class="form-control-update form-control-comment" name="comment"
                        placeholder="Jūsų komentaras čia..." maxlength="400" id="id_comment"></textarea>
                    {% if comment_form.errors %}
                    {% for field in comment_form %}
                    {% for error in field.errors %}
                    <p class="invalid-feedback-custom"><strong>{{ error|escape }}</strong></p>
                    {% endfor %}
                    {% endfor %}
                    {% endif %}
                    <button class="btn btn-custom btn-outline-info" id="btn-upload3" type="submit">Skelbti</button>
                </form>
                {% else %}
                <h5>Esate neprisijungęs, kad rašyti komentarus</h5>
                <a style="text-decoration: none;" href="{% url 'login' %}"><button
                        class="btn btn-custom btn-outline-info" id='btn-upload3' type="submit">Prisijungti</button></a>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

web_app/templates/web_app/post_upload.html
{% extends 'web_app/base.html' %}
{% load crispy_forms_tags %}

{% block css %}
<style>
    @media only screen and (max-height: 800px) {
        #btn-upload1 {
            margin-top: 83px;
        }
    }
</style>
{% endblock css %}

{% block content %}
<section class="main main-fixed">
    <div class="container container-fixed">
        <form action="" method="POST" enctype="multipart/form-data" novalidate
            onsubmit="return IkeltiVideoValidatorius()">
            <!--return stops the submission of form-->
            {% csrf_token %}
            <!-- {{ form|crispy }} -->
            <div id='div_id_title' class="form-group">
                <label for="id_title" class="requiredField">Antraštė</label>
                <div>
                    <input id="id_title" type="text" name="title" maxlength="150" autocapitalize="none"
                        class="textinput textInput form-control" required>
                    <p id="error_title_required" class="invalid-feedback"></p>
                </div>
            </div>
            <div id='div_id_video' class="form-group">
                <label for="id_video">Įkelti video</label>
                <div class="custom-file">
                    <input type="file" name="video" accept="video/*" required id="id_video"
                        class="clearablefileinput custom-file-input">
                    <p id="error_video_required" class="invalid-feedback" style="margin-top: 15px;"></p>
                    <label for="id_video" id='video-text-color'
                        class="requiredField form-control custom-file-label">Spauskite
                        čia...</label>
                </div>
            </div>
            <button class="btn btn-custom btn-outline-info" id='btn-upload1' type="submit">Skelbti</button>
        </form>
    </div>
</section>
{% endblock content %}